<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
    <Version>26.9.0.0</Version>
    <Authors>Matthias Burger</Authors>
    <Company>Matthias Burger</Company>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>This package provides useful extension-methods for C# .NET Standard.</Description>
    <PackageTags>Extension, Extensions, Extensionmethods</PackageTags>
    <PackageLicenseUrl></PackageLicenseUrl>
    <LangVersion>latest</LangVersion>
    <PackageProjectUrl>https://matthiasburger.github.io/IronSphere.Extensions</PackageProjectUrl>
    <RepositoryUrl>https://github.com/matthiasburger/IronSphere.Extensions</RepositoryUrl>
    <FileVersion>26.9.0.0</FileVersion>
    <NeutralLanguage></NeutralLanguage>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <AssemblyVersion>26.9.0.0</AssemblyVersion>
    <PackageVersion>26.9.0.1</PackageVersion>
    <AssemblyOriginatorKeyFile>ironsphere_extensions.pfx</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <Nullable>enable</Nullable>
    <PackageReleaseNotes></PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net462|AnyCPU'">
    <DocumentationFile>IronSphere.Extensions.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageReference Include="System.ValueTuple" Version="4.6.2" />
  </ItemGroup>
  
</Project>
